apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: metrics-errors-trigger
spec:
  broker: rules-results
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: metrics-errors
---
